name: Daily News Fetch

on:
  schedule:
    # Runs at 4 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run news fetch script
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: python3 bing.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results/result.json
        git commit -m "Update news data" -a || exit 0
        git push
